version: "3"

services:
  pmps_backend_db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pmpsdbuser
      - POSTGRES_PASSWORD=pmpsdbpass
      - POSTGRES_DB=pmps_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - main


  pmps_api:
    build: .
    command: bash -c "alembic upgrade heads && uvicorn app.root.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/pmps_backend
    ports:
      - 8000:8000
    depends_on:
      - pmps_backend_db
    networks:
      - main

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - "5050:80"
#    depends_on:
##      - db

networks:
 main:

volumes:
  pgdata: